#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
# Backup existing hosts file
cp /etc/hosts /etc/hosts.old
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
echo "127.0.0.2 localhost"